"use client";

import { useMemo, useState, useTransition } from "react";
import { CalendarDays, ChevronLeft, ChevronRight, Clock3, ExternalLink, MessageCircle, Plus, Scissors, Settings, Sparkles, Users, X } from "lucide-react";
import { acceptWhatsappRisk, createPromotion, queueGapFill, saveProfile, saveService, setAppointmentStatus } from "@/app/actions/turnos";
import { MagnetLogo } from "./magnet-logo";
import Image from "next/image";

type Screen = "agenda" | "clientes" | "promos" | "servicios" | "ajustes";
const money = (cents: number) => new Intl.NumberFormat("es-AR", { style: "currency", currency: "ARS", minimumFractionDigits: 0 }).format(cents / 100);
const dayKey = (d: Date) => d.toISOString().slice(0, 10);
const localDay = (d: Date) => new Intl.DateTimeFormat("en-CA", { timeZone: "America/Argentina/Buenos_Aires" }).format(d);
const wa = (phone: string, text: string) => `https://wa.me/54${phone.replace(/\D/g, "")}?text=${encodeURIComponent(text)}`;

export function AppShell({ data }: { data: any }) {
  const [screen, setScreen] = useState<Screen>("agenda");
  const [date, setDate] = useState(new Date());
  const [view, setView] = useState<"dia" | "semana" | "mes">("dia");
  const [sheet, setSheet] = useState<any>(null);
  const [pending, start] = useTransition();
  const accent = data.profile?.accent ?? "#E94F37";
  const appointments = data.appointments.map((a: any) => ({ ...a, startsAt: new Date(a.startsAt), endsAt: new Date(a.endsAt) }));
  const selected = appointments.filter((a: any) => localDay(a.startsAt) === localDay(date) && a.status !== "CANCELADO");

  const nav = (to: Screen) => { setScreen(to); setSheet(null); };
  return (
    <div className="turnos-app" style={{ "--acento": accent } as React.CSSProperties}>
      <header className="topbar">
        <button className="brand" onClick={() => nav("agenda")}><MagnetLogo particles /><span><b>Imán</b><small>{data.profile?.name ?? data.tenant.name}</small></span></button>
        <a className="pill ghost" href={`/reservar/${data.tenant.slug}`} target="_blank">Compartir <ExternalLink size={16} /></a>
      </header>
      <main className={`screen ${screen === "agenda" ? "with-fab" : ""}`}>
        {screen === "agenda" && <Agenda date={date} setDate={setDate} view={view} setView={setView} appointments={appointments} selected={selected} hours={data.workingHours} clients={data.clients} onSheet={setSheet} />}
        {screen === "clientes" && <Clients clients={data.clients} profile={data.profile} />}
        {screen === "promos" && <Promos services={data.services} promotions={data.promotions} slug={data.tenant.slug} onCreate={() => setSheet({ type: "promo" })} />}
        {screen === "servicios" && <Services services={data.services} hours={data.workingHours} onCreate={() => setSheet({ type: "service" })} />}
        {screen === "ajustes" && <SettingsScreen data={data} onEdit={() => setSheet({ type: "profile" })} onWhatsapp={() => setSheet({ type: "whatsapp" })} onAccent={(accent:string)=>start(async()=>{await saveProfile({name:data.profile.name,phone:data.profile.phone??"",address:data.profile.address??"",instagram:data.profile.instagram??"",accent});location.reload()})} />}
      </main>
      {screen === "agenda" && <button className="fab" aria-label="Agendar turno" onClick={() => setSheet({ type: "manual" })}><Plus /></button>}
      <nav className="tabbar">
        <Tab active={screen === "agenda"} icon={<CalendarDays />} label="Agenda" onClick={() => nav("agenda")} />
        <Tab active={screen === "clientes"} icon={<Users />} label="Clientes" onClick={() => nav("clientes")} />
        <Tab active={screen === "promos"} icon={<Sparkles />} label="Promos" onClick={() => nav("promos")} />
        <Tab active={screen === "servicios"} icon={<Scissors />} label="Servicios" onClick={() => nav("servicios")} />
        <Tab active={screen === "ajustes"} icon={<Settings />} label="Ajustes" onClick={() => nav("ajustes")} />
      </nav>
      {sheet && <Sheet onClose={() => setSheet(null)}>
        {sheet.type === "gap" && <GapSheet auto={data.tenant.plan === "TURNOS_AUTO" && !!data.tenant.whatsappRiskAcceptedAt} pending={pending} gap={sheet.gap} clients={data.clients} profile={data.profile} onAuto={(startLabel:string,endLabel:string)=>start(async()=>{const count=await queueGapFill(startLabel,endLabel);alert(`${count} mensajes quedaron en cola.`)})} />}
        {sheet.type === "appointment" && <AppointmentSheet appointment={sheet.appointment} pending={pending} run={(status: any) => start(async () => { await setAppointmentStatus(sheet.appointment.id, status); location.reload(); })} />}
        {sheet.type === "service" && <ServiceForm pending={pending} onSave={(form: any) => start(async () => { await saveService(form); location.reload(); })} />}
        {sheet.type === "promo" && <PromoForm services={data.services} pending={pending} onSave={(form: any) => start(async () => { await createPromotion(form); location.reload(); })} />}
        {sheet.type === "profile" && <ProfileForm profile={data.profile} pending={pending} onSave={(form: any) => start(async () => { await saveProfile(form); location.reload(); })} />}
        {sheet.type === "whatsapp" && <WhatsappConsent qr={data.whatsapp?.qrCode} eligible={data.tenant.plan === "TURNOS_AUTO"} pending={pending} accepted={!!data.tenant.whatsappRiskAcceptedAt} onAccept={() => start(async () => { await acceptWhatsappRisk(); location.reload(); })} />}
        {sheet.type === "manual" && <ManualHook slug={data.tenant.slug} />}
      </Sheet>}
    </div>
  );
}

function Tab({ active, icon, label, onClick }: any) { return <button className={active ? "active" : ""} onClick={onClick}>{icon}<span>{label}</span><i /></button>; }

function Agenda({ date, setDate, view, setView, appointments, selected, hours, clients, onSheet }: any) {
  const days = Array.from({ length: 7 }, (_, i) => { const d = new Date(date); d.setDate(date.getDate() - 3 + i); return d; });
  return <>
    <section className="agenda-head">
      <div><p className="eyebrow">TU DÍA, SIN HUECOS</p><h1>{localDay(date) === localDay(new Date()) ? "Hoy" : date.toLocaleDateString("es-AR", { weekday: "long", day: "numeric", month: "short" })}</h1></div>
      <div className="segmented"><button className={view === "dia" ? "on" : ""} onClick={() => setView("dia")}>Día</button><button className={view === "semana" ? "on" : ""} onClick={() => setView("semana")}>Semana</button><button className={view === "mes" ? "on" : ""} onClick={() => setView("mes")}>Mes</button></div>
    </section>
    <div className="week-strip">{days.map((d) => <button key={dayKey(d)} className={`${localDay(d) === localDay(date) ? "selected" : ""} ${localDay(d) === localDay(new Date()) ? "today" : ""}`} onClick={() => setDate(d)}><small>{d.toLocaleDateString("es-AR", { weekday: "short" }).slice(0, 2)}</small><b>{d.getDate()}</b><span>{appointments.filter((a: any) => localDay(a.startsAt) === localDay(d) && a.status !== "CANCELADO").slice(0, 3).map((_: any, i: number) => <i key={i} />)}</span></button>)}</div>
    {view === "semana" ? <WeekGrid days={days} appointments={appointments} onSelect={(a: any) => { setDate(a.startsAt); onSheet({ type: "appointment", appointment: a }); }} /> : view === "mes" ? <MonthGrid date={date} appointments={appointments} onSelect={(day: Date) => { setDate(day); setView("dia"); }} /> : <Timeline date={date} items={selected} hours={hours} clients={clients} onSheet={onSheet} />}
  </>;
}

function Timeline({ date, items, hours, clients, onSheet }: any) {
  const weekday = date.getDay();
  const dayHours = hours.filter((h: any) => h.weekday === weekday && h.active);
  if (!dayHours.length) return <div className="empty"><span>🌙</span><h3>Hoy está cerrado</h3><p>Un día libre también ordena la agenda.</p></div>;
  const start = dayHours[0].startMinutes, end = dayHours.at(-1).endMinutes;
  const rows: any[] = []; let cursor = start;
  for (const a of items) {
    const m = a.startsAt.getHours() * 60 + a.startsAt.getMinutes();
    if (m > cursor + 14) rows.push({ type: "gap", start: cursor, end: m });
    rows.push({ type: "appointment", appointment: a });
    cursor = Math.max(cursor, a.endsAt.getHours() * 60 + a.endsAt.getMinutes());
  }
  if (cursor < end) rows.push({ type: "gap", start: cursor, end });
  const futureGap = rows.find((r) => r.type === "gap" && localDay(date) >= localDay(new Date()) && (localDay(date) > localDay(new Date()) || r.end > new Date().getHours() * 60 + new Date().getMinutes()));
  return <div className="timeline">{rows.map((row, index) => row.type === "appointment" ? <AppointmentCard key={row.appointment.id} appointment={row.appointment} onClick={() => onSheet({ type: "appointment", appointment: row.appointment })} /> : <GapCard key={`g${index}`} gap={row} loud={row === futureGap} clients={clients} onClick={() => onSheet({ type: "gap", gap: row })} />)}</div>;
}

function AppointmentCard({ appointment: a, onClick }: any) { return <div className="timeline-row"><time>{a.startsAt.toLocaleTimeString("es-AR", { hour: "2-digit", minute: "2-digit" })}</time><button className={`appointment ${a.status.toLowerCase().replace("_", "-")}`} onClick={onClick}><span className="avatar">{a.client.name.split(" ").map((x: string) => x[0]).slice(0, 2).join("")}</span><span><b>{a.client.name}</b><small>{a.service.emoji} {a.service.name} · {a.service.durationMinutes} min</small></span><em>{money(a.service.priceCents)}</em></button></div>; }
function GapCard({ gap, loud, clients, onClick }: any) { const fmt = (m: number) => `${String(Math.floor(m / 60)).padStart(2, "0")}:${String(m % 60).padStart(2, "0")}`; return <div className="timeline-row"><time>{fmt(gap.start)}</time><button className={`gap ${loud ? "loud" : ""}`} onClick={onClick}><span><b>{fmt(gap.start)}—{fmt(gap.end)} <i>zzz</i></b><small>{Math.floor((gap.end-gap.start)/60) ? `${Math.floor((gap.end-gap.start)/60)} h ` : ""}{(gap.end-gap.start)%60 || ""} libres · {clients.filter((c: any) => recurrence(c).tone !== "ok").length} clientes para avisar</small></span>{loud ? <strong>LLENAR HUECO</strong> : <Plus />}</button></div>; }

function WeekGrid({ days, appointments, onSelect }: any) { return <div className="week-grid">{days.map((day: Date) => <div key={dayKey(day)}><h3>{day.toLocaleDateString("es-AR", { weekday: "short", day: "numeric" })}</h3>{appointments.filter((a: any) => localDay(a.startsAt) === localDay(day) && a.status !== "CANCELADO").map((a: any) => <button key={a.id} onClick={() => onSelect(a)}><time>{a.startsAt.toLocaleTimeString("es-AR", { hour: "2-digit", minute: "2-digit" })}</time><b>{a.client.name.split(" ")[0]}</b><small>{a.service.name}</small></button>)}</div>)}</div>; }
function MonthGrid({ date, appointments, onSelect }: any) { const first=new Date(date.getFullYear(),date.getMonth(),1);const start=new Date(first);start.setDate(first.getDate()-first.getDay());const days=Array.from({length:42},(_,i)=>{const d=new Date(start);d.setDate(start.getDate()+i);return d});return <div className="month-grid">{["Dom","Lun","Mar","Mié","Jue","Vie","Sáb"].map(x=><b key={x}>{x}</b>)}{days.map(d=>{const count=appointments.filter((a:any)=>localDay(a.startsAt)===localDay(d)&&a.status!=="CANCELADO").length;return <button key={dayKey(d)} className={`${d.getMonth()!==date.getMonth()?"outside":""} ${localDay(d)===localDay(new Date())?"today":""}`} onClick={()=>onSelect(d)}><span>{d.getDate()}</span>{count>0&&<small>{count} turno{count>1?"s":""}</small>}</button>})}</div>}

function recurrence(c: any) { const last = c.appointments?.[0] ? new Date(c.appointments[0].startsAt) : null; if (!last || !c.expectedCycleDays) return { tone: "due", label: "Sin ciclo" }; const days = Math.floor((Date.now() - last.getTime()) / 86400000); const ratio = days / c.expectedCycleDays; return ratio >= 1.2 ? { tone: "late", label: `${days - c.expectedCycleDays} días vencido` } : ratio >= .85 ? { tone: "due", label: "Le toca ahora" } : { tone: "ok", label: "Al día" }; }
function Clients({ clients, profile }: any) { const [query, setQuery] = useState(""); return <><p className="eyebrow">RECURRENCIA REAL</p><h1>Clientes</h1><div className="search"><Users /><input placeholder="Buscá por nombre o WhatsApp" value={query} onChange={(e) => setQuery(e.target.value)} /></div><div className="client-list">{clients.filter((c: any) => `${c.name}${c.phone}`.toLowerCase().includes(query.toLowerCase())).sort((a: any,b: any) => recurrence(a).tone === "late" ? -1 : 1).map((c: any) => { const r=recurrence(c); return <article className="client-card" key={c.id}><span className="avatar">{c.name.split(" ").map((x:string)=>x[0]).slice(0,2).join("")}</span><div><b>{c.name}</b><small>{c.phone}</small><span className={`semaphore ${r.tone}`}>{r.label}</span></div><a className="wa-button" href={wa(c.phone, `Hola ${c.name.split(" ")[0]} 👋 ¿Querés reservar tu próximo turno en ${profile.name}?`)} target="_blank" aria-label={`WhatsApp a ${c.name}`}><MessageCircle /></a></article>; })}</div></>; }

function Promos({ services, promotions, slug, onCreate }: any) { return <><p className="eyebrow">CREALA EN 3 TOQUES</p><div className="title-row"><h1>Promos</h1><button className="pill accent" onClick={onCreate}><Plus /> Crear</button></div><div className="hint-card"><Sparkles /><div><b>Primero sumá valor</b><p>Un lavado, perfilado o café vende mejor que bajar el precio.</p></div></div><div className="cards">{promotions.map((p:any)=><article className="promo-card" key={p.id}><span>{p.kind === "ADD_ON" ? "🎁" : "⚡"}</span><div><b>{p.name}</b><p>{p.message}</p><small>Vence {new Date(p.expiresAt).toLocaleDateString("es-AR")}</small></div><a className="round-button" target="_blank" href={`/reservar/${slug}?promo=${p.token}`}><ExternalLink /></a></article>)}</div></>; }
function Services({ services, hours, onCreate }: any) { return <><p className="eyebrow">TU MENÚ Y TU SEMANA</p><div className="title-row"><h1>Servicios</h1><button className="pill accent" onClick={onCreate}><Plus /> Nuevo</button></div><div className="cards">{services.map((s:any)=><article className="service-card" key={s.id}><span>{s.emoji}</span><div><b>{s.name}</b><small>{s.durationMinutes} min · {money(s.priceCents)}</small></div><i className={s.active ? "on" : ""}>{s.active ? "Activo" : "Pausado"}</i></article>)}</div><h2 className="section-title">Horarios</h2><div className="hours-card">{["Dom","Lun","Mar","Mié","Jue","Vie","Sáb"].map((d,i)=>{const h=hours.find((x:any)=>x.weekday===i);return <div key={d}><b>{d}</b><span>{h ? `${Math.floor(h.startMinutes/60)}:${String(h.startMinutes%60).padStart(2,"0")} — ${Math.floor(h.endMinutes/60)}:${String(h.endMinutes%60).padStart(2,"0")}` : "Cerrado"}</span></div>})}</div></>; }
function SettingsScreen({ data, onEdit, onWhatsapp, onAccent }: any) { const health=data.whatsapp?.health??"DISCONNECTED"; return <><p className="eyebrow">A TU MANERA</p><h1>Ajustes</h1><button className="settings-card" onClick={onEdit}><span className="avatar big">{data.profile.name.slice(0,2).toUpperCase()}</span><div><b>{data.profile.name}</b><small>{data.profile.address}</small><span className="accent-dot" style={{background:data.profile.accent}} /></div><ChevronRight /></button><h2 className="section-title">Tema de tu marca</h2><div className="palette">{["#E94F37","#C5386A","#7656D6","#246BCE","#087E8B","#198754","#C26A12","#33231A"].map(c=><button aria-label={`Usar color ${c}`} onClick={()=>onAccent(c)} key={c} style={{background:c}} className={`palette-swatch ${c===data.profile.accent?"selected":""}`}/>)}</div><h2 className="section-title">Turnos Auto</h2><button className="settings-card" onClick={onWhatsapp}><span className={`health ${health.toLowerCase()}`} /><div><b>WhatsApp automático</b><small>{health === "CONNECTED" ? "Conectado y saludable" : health === "QR_PENDING" ? "Esperando que escanees el QR" : "Desconectado · usa links wa.me"}</small></div><ChevronRight /></button><div className="deposit-hook"><span>🔒</span><div><b>Señas para reservas</b><p>Preparado en datos, todavía no disponible.</p></div><em>Próximamente</em></div></>; }

function Sheet({ children, onClose }: any) { return <div className="sheet-backdrop" onMouseDown={(e)=>e.target===e.currentTarget&&onClose()}><aside className="sheet"><div className="handle"/><button className="sheet-close" onClick={onClose}><X /></button>{children}</aside></div>; }
function GapSheet({ gap, clients, profile, auto, onAuto, pending }: any) { const due=clients.filter((c:any)=>recurrence(c).tone!=="ok").slice(0,5);const fmt=(m:number)=>`${String(Math.floor(m/60)).padStart(2,"0")}:${String(m%60).padStart(2,"0")}`;return <><p className="eyebrow">LLENAR HUECO</p><h2>¿A quién le toca volver?</h2><p className="sheet-intro">Elegimos clientes por su ciclo real de visitas.</p>{auto&&<button className="button accent" disabled={pending} onClick={()=>onAuto(fmt(gap.start),fmt(gap.end))}><Sparkles/> Poner {due.length} mensajes en cola</button>}{due.map((c:any)=><a className="client-card compact" key={c.id} target="_blank" href={wa(c.phone,`Hola ${c.name.split(" ")[0]} 👋 Se liberó un lugar hoy en ${profile.name}. ¿Te viene bien?`)}><span className="avatar">{c.name[0]}</span><div><b>{c.name}</b><span className={`semaphore ${recurrence(c).tone}`}>{recurrence(c).label}</span></div><MessageCircle /></a>)}</>; }
function AppointmentSheet({ appointment:a, run, pending }:any){return <><p className="eyebrow">DETALLE DEL TURNO</p><h2>{a.client.name}</h2><p className="sheet-intro">{a.service.emoji} {a.service.name} · {a.startsAt.toLocaleString("es-AR",{weekday:"long",hour:"2-digit",minute:"2-digit"})}</p><a className="button wa" href={wa(a.client.phone,`Hola ${a.client.name.split(" ")[0]}, te escribo por tu turno en ${a.startsAt.toLocaleTimeString("es-AR",{hour:"2-digit",minute:"2-digit"})}.`)} target="_blank"><MessageCircle/> Escribir por WhatsApp</a><div className="action-grid"><button disabled={pending} onClick={()=>run("ASISTIO")}>✓ Asistió</button><button disabled={pending} onClick={()=>run("NO_VINO")}>No vino</button><button className="danger" disabled={pending} onClick={()=>run("CANCELADO")}>Cancelar turno</button></div></>}
function ServiceForm({onSave,pending}:any){const [form,set]=useState({name:"",emoji:"✂️",durationMinutes:40,priceCents:900000});return <form onSubmit={e=>{e.preventDefault();onSave(form)}}><p className="eyebrow">NUEVO SERVICIO</p><h2>¿Qué ofrecés?</h2><Field label="Nombre"><input required value={form.name} onChange={e=>set({...form,name:e.target.value})}/></Field><div className="form-row"><Field label="Emoji"><input value={form.emoji} onChange={e=>set({...form,emoji:e.target.value})}/></Field><Field label="Duración"><select value={form.durationMinutes} onChange={e=>set({...form,durationMinutes:+e.target.value})}><option value="30">30 min</option><option value="40">40 min</option><option value="45">45 min</option><option value="60">60 min</option></select></Field></div><Field label="Precio"><input type="number" value={form.priceCents/100} onChange={e=>set({...form,priceCents:+e.target.value*100})}/></Field><button className="button accent" disabled={pending}>Guardar servicio</button></form>}
function PromoForm({services,onSave,pending}:any){const [form,set]=useState({serviceId:services[0]?.id,name:"Corte + regalo",addOnLabel:"Perfilado de cejas",message:"Reservá hoy y te sumamos un perfilado sin cargo.",expiresAt:new Date(Date.now()+7*86400000)});return <form onSubmit={e=>{e.preventDefault();onSave(form)}}><p className="eyebrow">3 TOQUES</p><h2>Armá una promo</h2><Field label="1. Servicio"><select value={form.serviceId} onChange={e=>set({...form,serviceId:e.target.value})}>{services.map((s:any)=><option key={s.id} value={s.id}>{s.name}</option>)}</select></Field><Field label="2. Sumale algo"><input value={form.addOnLabel} onChange={e=>set({...form,addOnLabel:e.target.value,name:`${services.find((s:any)=>s.id===form.serviceId)?.name} + regalo`})}/></Field><Field label="3. Mensaje"><textarea value={form.message} onChange={e=>set({...form,message:e.target.value})}/></Field><button className="button accent" disabled={pending}>Crear link de promo</button></form>}
function ProfileForm({profile,onSave,pending}:any){const [form,set]=useState({name:profile.name,phone:profile.phone??"",address:profile.address??"",instagram:profile.instagram??"",accent:profile.accent});return <form onSubmit={e=>{e.preventDefault();onSave(form)}}><p className="eyebrow">TU NEGOCIO</p><h2>Datos y color</h2>{["name","phone","address","instagram"].map(key=><Field key={key} label={({name:"Nombre",phone:"WhatsApp",address:"Dirección",instagram:"Instagram"} as any)[key]}><input value={(form as any)[key]} onChange={e=>set({...form,[key]:e.target.value})}/></Field>)}<Field label="Color de marca"><input type="color" value={form.accent} onChange={e=>set({...form,accent:e.target.value})}/></Field><button className="button accent" disabled={pending}>Guardar cambios</button></form>}
function WhatsappConsent({eligible,accepted,onAccept,pending,qr}:any){if(!eligible)return <><p className="eyebrow">TURNOS AUTO</p><h2>Automatizá desde tu número</h2><p className="sheet-intro">Confirmaciones, recordatorios y recupero con cola y ritmo humano.</p><a className="button accent" href="/suscripcion">Subir a Turnos Auto</a></>;return <><p className="eyebrow">TURNOS AUTO</p><h2>{accepted?"Vinculá tu WhatsApp":"Antes de activarlo"}</h2>{accepted?<div className="qr-placeholder">{qr?<Image src={qr} width={220} height={220} unoptimized alt="Código QR para vincular WhatsApp"/>:<div>QR</div>}<p>{qr?"WhatsApp → Dispositivos vinculados → Vincular dispositivo.":"El worker está preparando el código de tu sesión aislada."}</p></div>:<div className="risk"><b>Integración no oficial</b><p>Turnos Auto usa open-wa para enviar desde tu número. WhatsApp puede limitar o bloquear cuentas que usen automatizaciones. Usamos ritmo humano, límites y pausas, pero el riesgo no desaparece.</p><p>Si la sesión falla, Imán sigue funcionando y vuelve automáticamente a links wa.me.</p><button className="button accent" disabled={pending} onClick={onAccept}>Entiendo el riesgo y acepto</button></div>}</>}
function ManualHook({slug}:any){return <><p className="eyebrow">NUEVO TURNO</p><h2>Agendalo desde disponibilidad</h2><p className="sheet-intro">La carga manual usa el mismo motor race-safe que tu página pública.</p><a className="button accent" href={`/reservar/${slug}`} target="_blank">Elegir servicio y horario <ExternalLink/></a></>}
function Field({label,children}:any){return <label className="field"><span>{label}</span>{children}</label>}
