"use client";
import { useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import { Check, Clock3, Scissors, Sparkles } from "lucide-react";
import { elegirPlan } from "@/app/actions/billing";
import { ensureDefaultWorkingHours, saveProfile, saveService } from "@/app/actions/turnos";
import { MagnetLogo } from "./magnet-logo";

export function OnboardingFlow({ tenantName }: { tenantName: string }) {
  const [step,setStep]=useState(0); const [pending,start]=useTransition(); const router=useRouter();
  const [business,setBusiness]=useState({name:tenantName,phone:"",address:"",instagram:"",accent:"#E94F37"});
  const [service,setService]=useState({name:"Corte clásico",emoji:"✂️",durationMinutes:40,priceCents:900000});
  const nextBusiness=()=>start(async()=>{await Promise.all([saveProfile(business),ensureDefaultWorkingHours()]);setStep(1)});
  const nextService=()=>start(async()=>{await saveService(service);setStep(2)});
  const finish=(plan:"TURNOS"|"TURNOS_AUTO")=>start(async()=>{await elegirPlan(plan);router.push("/app");router.refresh()});
  return <main className="booking-page" style={{maxWidth:560}}><header className="booking-brand"><MagnetLogo particles/><div><b>Imán Turnos</b><small>Listo en menos de 3 minutos</small></div></header><div className="booking-progress">{[0,1,2].map(i=><i key={i} className={i<=step?"on":""}/>)}</div>
    {step===0&&<section><p className="eyebrow">1 DE 3 · TU NEGOCIO</p><h1>Dale tu identidad</h1><p className="sheet-intro">Este color también va a aparecer en tu página pública.</p><label className="field"><span>Nombre</span><input value={business.name} onChange={e=>setBusiness({...business,name:e.target.value})}/></label><label className="field"><span>WhatsApp</span><input value={business.phone} onChange={e=>setBusiness({...business,phone:e.target.value})}/></label><label className="field"><span>Dirección</span><input value={business.address} onChange={e=>setBusiness({...business,address:e.target.value})}/></label><label className="field"><span>Color de marca</span><input type="color" value={business.accent} onChange={e=>setBusiness({...business,accent:e.target.value})}/></label><button className="button accent" disabled={pending||!business.name} onClick={nextBusiness}>Seguir</button></section>}
    {step===1&&<section><p className="eyebrow">2 DE 3 · PRIMER SERVICIO</p><h1>¿Qué pueden reservar?</h1><div className="hint-card"><Scissors/><div><b>Empezá con uno</b><p>Después agregás todos los que quieras.</p></div></div><label className="field"><span>Servicio</span><input value={service.name} onChange={e=>setService({...service,name:e.target.value})}/></label><div className="form-row"><label className="field"><span>Duración</span><select value={service.durationMinutes} onChange={e=>setService({...service,durationMinutes:+e.target.value})}><option value="30">30 min</option><option value="40">40 min</option><option value="45">45 min</option><option value="60">60 min</option></select></label><label className="field"><span>Precio</span><input type="number" value={service.priceCents/100} onChange={e=>setService({...service,priceCents:+e.target.value*100})}/></label></div><button className="button accent" disabled={pending||!service.name} onClick={nextService}>Crear servicio</button></section>}
    {step===2&&<section><p className="eyebrow">3 DE 3 · TU PLAN</p><h1>Probalo 14 días</h1><p className="sheet-intro">Todo trial empieza en el plan base. Podés activar Auto cuando quieras.</p><button className="settings-card" disabled={pending} onClick={()=>finish("TURNOS")}><Clock3/><div><b>Turnos · $ 15.000/mes</b><small>Agenda, reservas, clientes, promos, wa.me y email.</small></div><Check/></button><div className="hint-card"><Sparkles/><div><b>Después podés subir a Turnos Auto</b><p>$ 25.000/mes · confirmaciones y recordatorios automáticos.</p></div></div><button className="button accent" disabled={pending} onClick={()=>finish("TURNOS")}>{pending?"Preparando tu agenda…":"Empezar mi prueba gratis"}</button><p style={{fontSize:12,color:"var(--tinta-suave)",textAlign:"center"}}>No se cobra nada ahora. Mercado Pago se vincula antes de terminar el trial.</p></section>}
  </main>;
}
